version: "3.7"

services:
  database_lotery:
    image: postgres
    container_name: database_lotery
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_lotery
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: bet_lotery
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      -  database_lotery
    depends_on:
      -  database_lotery


volumes:
  pgdata:
    driver: local
